# Generated by Django 4.2.13 on 2024-07-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('fruit', '과일'), ('seed', '모종')], max_length=20)),
                ('price_per_small', models.DecimalField(decimal_places=0, max_digits=10)),
                ('price_per_big', models.DecimalField(decimal_places=0, max_digits=10)),
                ('price_per_unit', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
