# Generated by Django 5.2.2 on 2025-06-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_name_alter_item_price_per_big_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/images/'),
        ),
    ]
