# Generated by Django 4.2.13 on 2024-07-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='size',
            field=models.CharField(choices=[('small', '소과'), ('big', '대과'), ('none', '해당 없음(모종)')], default=1, max_length=5),
            preserve_default=False,
        ),
    ]
