# Generated by Django 4.2.13 on 2024-07-10 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_detail_address_order_extra_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='extra_address',
        ),
    ]
