# Generated by Django 4.2.13 on 2024-07-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_extra_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='review_written',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('fruit', '과일'), ('seed', '모종')], max_length=20),
        ),
    ]
