# Generated by Django 4.2.13 on 2024-07-11 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_item'),
        ('items', '0002_alter_item_name_alter_item_price_per_big_and_more'),
        ('orders', '0004_order_review_written_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
