# Generated by Django 5.2.2 on 2025-06-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_generate_order_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(blank=True, choices=[('small', '소과1kg'), ('big', '대과1kg'), ('none', '모종(해당없음)')], max_length=5, null=True),
        ),
    ]
