name: Deploy to EC2

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          echo "Deploying to EC2 host: $EC2_HOST"
          ssh -v ubuntu@$EC2_HOST '
            cd /home/ubuntu/blueberry &&
            git pull origin master &&
            source venv/bin/activate &&
            pip install -r requirements.txt &&
            python manage.py migrate &&
            python manage.py collectstatic --noinput &&
            sudo systemctl restart blueberry'